export  const REACT_APP_API_URL="http://localhost:5000/api"
export  const REACT_APP_URL="http://localhost:5000/"
export  const REACT_APP_Client_URL="http://localhost:3000"
export  const REACT_APP_CLIENT_MAP="http://localhost:5000/map"
export  const REACT_APP_CLIENT_INTRO="http://localhost:5000/intro"
export  const REACT_APP_BACKEND_URL="http://localhost:4000/"